### PR TITLE
feat: File attachments

### LINKED ISSUE #859: File Attachments
This has been requested several times recently. Initial plan would be to integrate with the two largest storage providers, _Google Drive_ and _Dropbox_, rather than building our own file storage service.

On a document you should be able to:

- Attach a file
- Pick an existing file from GDrive/Dropbox or upload
- See a list of files attached to doc
- See which docs have files attached
- Search for files attached to docs

**As always, please add reactions to this issue to vote for it to be implemented 😄**

### PR DESCRIPTION
**Pull request by tommoor**
### Todo

- [x] Handle files without a known mimetype
- [x] `FileExtension` component handle files with no and long extension
- [x] Investigate 10% increase in bundle size (crypto module?) 😬 
- [x] Add and gracefully handle file size limit
- [x] Allow images to be uploaded as file attachments (useful for e.g. SVG resources)
- [x] Hook into `onProgress` event to render upload progress
- [x] Improve styling of placeholder
- [x] Fix bug with theme not updating in PM ComponentViews (This has always been an issue, but it's more pronounced with attachments)
- [x] Fix upload placeholder appears ontop of empty block placeholder
- [x] Handle underlying file has been deleted
- [x] Bump editor version
- [x] Handle upload failure in refactor
- [x] Markdown parse/serialize
- [x] Add block menu option
- [x] Handle paste/drag and drop
- [x] Refactor uploading logic, shared with images
- [x] Base styling, shared with disabled embeds
- [x] Shared pages

closes #859 
closes #2859

### CODE REVIEW

**Comment by tommoor** [comment]
I'm going to refactor this to not use a placeholder in favor of a full editor node while the upload is happening. The main benefit of this is:

- we can avoid style duplication
- we can avoid a bug in yjs with placeholders
- we can show the uploading progress to other users in the same doc at the same time

The downside is more complexity when/if the upload fails.

**Comment by tommoor** [comment]
This is ready to go – before it can be merged we need to perform some maintenance on the storage for Outline's cloud hosted customers.

**Comment by tommoor** [comment]
Planning to have maintenance complete this week

**Comment by Bence98007** [comment]
I see that this is merged, is it already in outline? Because I cannot find it in any menus, and Im using v.0.62.0

**Comment by tommoor** [comment]
The feature will be part of the next major release, `v0.63.0` – these are monthly.

**Comment by Bence98007** [comment]
Sounds good! :) Sorry for the unnecessary comment.

**Pull request merged**
