### PR TITLE
feat: add document level permissions

### PR DESCRIPTION
**Pull request by dolsem**
This PR adds what should be a reasonably efficient approach to document-level permissions.

Currently there are limitations:
* Users without collection-level edit permissions are not able to create nested documents, even if they have edit access to the parent document, because adding nested documents requires updating the collection (its document structure)
* Document permissions are not inhereted by child documents, to give someone access to a document and all of its children, permission should be granted individually for each document. If permissions are not granted on child documents, users with full permissions on the parent document will not be able to see child documents

Addresses #2359.

### CODE REVIEW

**Comment by shane-at-algo** [comment]
Any update on this feature ? Would be an amazing addition to have

**Comment by nullsumme** [comment]
I agree. Any update on this? It would be a shame if this PR gets closed without even discussing.

**Comment by sorvis** [comment]
This would be of help for our company as well. Are there potential risks that are holding this PR back from going?

**Comment by tommoor** [comment]
While some of this PR is inline with the plans for this feature, unfortunately much of the work here doesn't align with how we want to implement this permission system.

While the enthusiasm is appreciated – this is why we ask that contributors talk through their plans with the core team before starting on code rather than dump thousands of lines of code as a PR out of nowhere, it's always very unlikely to get merged in that scenario. It would take many hours just to even parse through the code here 😞 

This feature is still on the roadmap

**Pull request closed without merging**
