### PR TITLE
Webhook support for comments

### LINKED ISSUE #4931: Webhook support for comments

### PR DESCRIPTION
**Pull request by tommoor**
closes #4931

### CODE REVIEW

**Comment by stereo9** [comment]
@tommoor I just tested the webhooks for comments on v0.69.0 , by attaching it to a test webhook via webhook.site
it seems like comments don't trigger the request to be sent.
when assigning to all events though, the others seem to work without any problems

**Comment by tommoor** [comment]
Testing here it works as expected, which event specifically did you enable the hook for?

**Comment by stereo9** [comment]
thank you for the quick reply, which actually helped me to narrow down the problem.
i just clicked "all comment events"
image
but this didnt do the job. when selecting them individually it works like a charm.

**Comment by tommoor** [comment]
I think this bug is wider than comments, will create a new issue.

**Pull request merged**
