### PR TITLE
support local development with docker

### PR DESCRIPTION
**Pull request by sasso**
start local development with one command! (`make up`)

commands: 
* `make up` start all required services and run migrations
* `make build` rebuild docker image
* `make destroy` stop and remove all containers

### CODE REVIEW

**Comment by tommoor** [comment]
Hey @sasso, thanks for the PR! Going to checkout this out tonight properly but from a glance - looks great, this is something I've been meaning to setup for a while 😄

**Comment by sasso** [comment]
sounds good! I haven't implemented fakes3 yet but could be usefull to remove that dependency for local dev. It would be also nice to modify `.env.sample` to match hosts with docker-compose (postgres, redis) would make it even faster to bootstrap dev 😄

**Comment by tommoor** [comment]
@sasso I'm thinking I'll modify this to include as many env variables in the docker-compose file rather than in .env as possible for development, that way as you say getting going will be easier…

**Comment by sasso** [comment]
👍

**Pull request merged**
