### PR TITLE
feat: Port `scenes/Search` to functional component style

### LINKED ISSUE #3781: Port Search scene to functional style
While working on `UserFilter` I noticed that Search scene

https://github.com/outline/outline/blob/c3e149eb86e71f121fb8595575863b6395893391/app/scenes/Search/Search.tsx#L47

seems to be one of the few remaining class styled components, unlike its neighbors  

https://github.com/outline/outline/blob/c3e149eb86e71f121fb8595575863b6395893391/app/scenes/Document/index.tsx#L24

https://github.com/outline/outline/blob/c3e149eb86e71f121fb8595575863b6395893391/app/scenes/Login/index.tsx#L52

https://github.com/outline/outline/blob/c3e149eb86e71f121fb8595575863b6395893391/app/scenes/GroupMembers/GroupMembers.tsx#L24

https://github.com/outline/outline/blob/c3e149eb86e71f121fb8595575863b6395893391/app/scenes/GroupNew.tsx#L18

---

We could potentially look into porting it to functional style for readability and consistency

### PR DESCRIPTION
**Pull request by CuriousCorrelation**
# Description

PR ports `scene/Search/Search.tsx` to functional component style at `scene/Search/index.tsx`

# Issue
Closes  #3781 and  #3457

### CODE REVIEW

**Comment by tommoor** [comment]
It doesn't seem like changing the filters works any more without changing the search term…

**Comment by CuriousCorrelation** [comment]
I thought I was being smart relaying on dep array to check for change BUT forgot about the early escape on query match... :disappointed: 

Should be good now

**Review by tommoor — APPROVED** [review]

**Comment by tommoor** [comment]
Heads up – I had to revert this change as it was causing a DDOS in production – something is looping and making thousands of requests.

**Comment by CuriousCorrelation** [comment]
Sorry, that's quite bad.

This
https://github.com/outline/outline/blob/2a5077e3b1339e384cd604532a0abd02299090ab/app/scenes/Search/index.tsx#L91
is what might be causing a request buildup.

Likely some dependency of

https://github.com/outline/outline/blob/2a5077e3b1339e384cd604532a0abd02299090ab/app/scenes/Search/index.tsx#L68

or one of the `useEffect`.

I'll get this fixed ASAP

**Pull request merged**
