### PR TITLE
Update Slate

### PR DESCRIPTION
**Pull request by tommoor**
This is all the work in our code to update to the latest changes in Slate's API. The problem is we rely on a bunch of gitbook plugins that they haven't updated 😢 

closes https://github.com/outline/outline/issues/371
closes https://github.com/outline/outline/issues/242
closes https://github.com/outline/outline/issues/55

### CODE REVIEW

**Comment by tommoor** [comment]
Just did a plugin audit - looks like everything has finally been updated to support version 0.29/0.30 (the only difference on 0.30 is the removal of deprecated code paths).

Going to do this upgrade before I start on the comments issue as so many related API's change.

- **slate-collapse-on-escape** - `0.6.0` Supports 0.30.x
- **slate-edit-code** - `0.13.2` Supports 0.30.x
- **slate-edit-list** - `0.10.1` Supports 0.30.x
- **slate-md-serializer** - Supports 0.30.x on a branch, needs testing and merging
- **slate-paste-linkify** - `0.5.0` Supports 0.29.x
- **slate-prism** - `0.4.0` Supports 0.30.x
- **slate-trailing-block** - `0.4.0` Supports 0.29.x

**Comment by tommoor** [comment]
Lots of progress over the weekend and the API's and interfaces are much improved. Left to do:

- [ ] Checkboxes are not rendering correctly until you save (weird!)
- [ ] Image uploading does not display placeholder or image (however file does upload successfully)
- [ ] Creating a new block item from the toolbar leaves cursor on a new paragraph above
- [ ] Unfocusing block toolbar does not remove it

**Comment by tommoor** [comment]
@jorilallo this is now ready for more extensive testing. I've fixed all the major issues I can find but I'm sure there are a couple more hiding out in the corners if you get a chance to checkout and test sometime soon 😄

**Comment by jorilallo** [comment]
Found at least one bug that I was not able to repro in prod: when searching for a link, first arrow down selects the first search result and applies it as a link

**Comment by tommoor** [comment]
@jorilallo could you explain the bug better? That sounds like expected behavior to me.

**Pull request merged**
