### PR TITLE
feat: Asciinema embed support

### PR DESCRIPTION
**Pull request by Sevenn83**
I add embed support for Asciinema. I use gist embed as base, I don't really know if it's the best way to deal with <script> but it work.

Asciinema is a pretty cool free tool providing a record of your terminal input, very usefull to add demo on a wiki page.

### CODE REVIEW

**Comment by tommoor** [comment]
Thanks for the PR, I've been quite busy in the last week but will get to it this week

**Comment by tommoor** [comment]
Hi, got to reviewing this – there are two issues that I believe are preventing merge:

- There's a scrollbar inside the embed at least on chrome/macos it's possible to move the video up and down inside the iframe.
- In dark mode there is a bright white border around the embed, it looks like this:

image

**Comment by matbrgz** [comment]
@Sevenn83 could you please review it?

@tommoor could you please reopens?

**Comment by tommoor** [comment]
closing as this has been open since February without progress

**Pull request closed without merging**
