### PR TITLE
feat: add resize and Collapsed  menu 

### PR DESCRIPTION
**Pull request by teammaiscode**
Collapsed menu
image

Resize menu
image

### CODE REVIEW

**Review by teammaiscode — COMMENTED** [review]
ajustment

**Comment by teammaiscode** [comment]
referring pull request: https://github.com/outline/outline/issues/753

**Comment by tommoor** [comment]
Hi, thanks for proposing the PR to add this functionality. As it stands there are a few things that make this unmergable, let me know if you're interested in tackling them, if not no worries you can keep this work on your fork with no problems.

- The inclusion of an additional icon library in the form of material-ui/icons
- The inclusion of an entire new styling library, we use `styled-components` in this project
- Direct usage of `localStorage` for storing ui settings – I'd prefer to see this use the `UiStore` like other ui preferences, this store takes care of persistence.
- From a design point of view the extra space and separator above the team logo in the sidebar doesn't work too well, we can discuss where the controls should go if you'd like.

**Comment by tommoor** [comment]
Closing due to lack of response, collapsing has now been implemented (thanks for the inspiration) – we'd accept a PR for resizing that takes into account the feedback above and does not include new UI and icon libraries.

**Comment by MatheusRV** [comment]
@teammaiscode could you please review this? Resize is important to us.

**Pull request closed without merging**
