### PR TITLE
style: add option background for InputSelect

### PR DESCRIPTION
**Pull request by xphoniex**
This should fix https://github.com/outline/outline/issues/2015.
Please check with a Mac and leave a comment if it works.

### CODE REVIEW

**Comment by iamsaumya** [comment]
Hey @xphoniex, thanks for making an effort to put up a PR. 

The maintainer of the project had expressed his interest in solving this issue using custom input select ([here](https://github.com/outline/outline/issues/2015#issuecomment-851019380)). 

It's my fault for not updating the **Expected Behaviour** of the issue, and I will update it right away.

**Comment by tommoor** [comment]
If something this simple _does_ fix the background on Windows and not affect macOS then i'd be down with it as a patch until something custom is built

**Comment by iamsaumya** [comment]
On Ubuntu 

Screenshot from 2021-06-07 12-42-50

**Comment by tommoor** [comment]
image

MacOS continues to ignore it, so honestly this seems like a great stop-gap.

**Review by tommoor — APPROVED** [review]

**Pull request merged**
