### PR TITLE
chore: Bump mermaid dep for size decrease

### PR DESCRIPTION
**Pull request by tommoor**
Release notes: https://github.com/mermaid-js/mermaid/releases/tag/v9.3.0

### CODE REVIEW

**Comment by tommoor** [comment]
Blocked by https://github.com/mermaid-js/mermaid/pull/3914

**Comment by jensschaerer** [comment]
Seems that the blocking issue is fixed. Any chance to get the new Mermaid version for Outline soon?

**Comment by tommoor** [comment]
Afraid there has been no new version of Mermaid since the issue was fixed

**Comment by epipheus** [comment]
it's v10.0.2 now which has mindmaps can you please bump this for cloud.

**Pull request closed without merging**
