### PR TITLE
Collaborative editing

### PR DESCRIPTION
**Pull request by tommoor**
This branch was recently (Aug 2021) force-pushed to reflect a new approach to this feature.

- [ ] Alpha release (merge to `main`)

- [ ] Add ability to flag feature for admin in API
- [ ] Reduce `documents.info` fetches
- [ ] Add features UI in admin
- [ ] Image upload decorations

- [ ] Restore document functionality
- [ ] Redis scaling to multi-server
- [ ] Handle permissions changing while multiplayer is connected
- [ ] Handle `documents.update` API request should update CRDT state

### Done

- [x] Documentation for running multiplayer server
- [x] Sync failure after edit while offline and reconnect (https://github.com/ueberdosis/hocuspocus/issues/183)
- [x] Embeds not created when transforming to CRDT 
- [x] Content duplication issue (if converted to CRDT and not saved on server)
- [x] Move authentication from headers to websocket message (https://github.com/ueberdosis/hocuspocus/pull/163)
- [x] Refactor service architecture
- [x] Loading state when server takes >300ms to respond
- [x] Events added in multiplayer process not propagating to processors
- [x] Permission denied state/handling
- [x] Refactor so revision history, archived, deleted do not interact with multiplayer service
- [x] Tasks not updating with remote edit
- [x] Updating of todo tasks locally
- [x] Block restore document during beta
- [x] Add client storage
- [x] Show UI when websocket is disconnected to indicate lack of sync
- [x] Hook up awareness presence to avatar display
- [x] Add features validation
- [x] Templates functionality
- [x] read-only permissions
- [x] Bug: Documents being marked as "updated" when converting to CRDT
- [x] Move back to main `y-prosemirror` trunk away from personal fork
- [x] Improve "reconnecting…" state a little
- [x] Multi-process tracking
- [x] Bug: `url` not returned for new documents
- [x] Bug: "Publish" button for drafts leaves edit but doesn't publish
- [x] "New" badge appears erroneously on drafts
- [x] Bug: Content duplicated after sleep (may already be fixed, need to triple test)
- [x] Refactor so dhared docs do not interact with multiplayer service

related #811

### CODE REVIEW

**Comment by iamsaumya** [comment]
Please keep it open 😊

**Comment by nexflo** [comment]
Keep it open :D
Would love to hop over from notion ^^

**Comment by Hommus** [comment]
I've been looking forward to this update for a while and I've seen all the work you've been putting in lately. Just thought I would say keep up the good work!

**Comment by tommoor** [comment]
Thanks! As a sidenote much of the active development is happening as part of the Hocuspocus project right now which is private currently although it will be made public in the future under the MIT license.

**Comment by adelicato** [comment]
First of all, I wanna say "thank you" for this blessed feature that is coming to a project that is already beautiful. Now that I literally kissed your ass I wanna ask you how to setup the '**COLLABORATION_URL**' env variable in order to test the **alpha release**. Maybe you should provide an example in the documentation, thank you.

**Comment by ryanprior** [comment]
Congrats on landing this epic branch! 🥳 🧑🏻‍🤝‍🧑🏻 ✨

**Pull request merged**
