### PR TITLE
fix: Add max natural width logic to Images

### PR DESCRIPTION
**Pull request by lampy255**
If an exceptionally large image is added to a document, cap the natural width at 400 until the user overrides it with resize handles

### CODE REVIEW

**Comment by lampy255** [comment]
Open to feedback on this one.
My only concern is that existing documents with existing large images that have never been resized would have their width changed to 400 with this update..

**Comment by lampy255** [comment]
fixes #7039

**Comment by tommoor** [comment]
I think it's best to keep natural width to the correct value, to cap it at an arbitrary number for the purposes of display does feel wrong. I think the "correct" approach is probably a little more involved where we [modify transactions](https://prosemirror.net/docs/ref/version/0.17.0.html#state.Plugin.constructor^options.appendTransaction) that add an image to a table and write the width attribute to a value – something like half the document width?

**Comment by lampy255** [comment]
> I think it's best to keep natural width to the correct value, to cap it at an arbitrary number for the purposes of display does feel wrong. I think the "correct" approach is probably a little more involved where we [modify transactions](https://prosemirror.net/docs/ref/version/0.17.0.html#state.Plugin.constructor%5Eoptions.appendTransaction) that add an image to a table and write the width attribute to a value – something like half the document width?

Yeah this sounds like a better approach.
I'll have another go at this.

**Comment by lampy255** [comment]
Ok unfortunately this approach is a little too far outside my React skill level. Will close this PR for now.

**Pull request closed without merging**
