### PR TITLE
feat: add document events log menu

### PR DESCRIPTION
**Pull request by guilherme-diniz**
Add events menu to a document, allowing us to see it events.
Screen Shot 2020-08-21 at 22 31 13
Screen Shot 2020-08-21 at 22 31 24

### CODE REVIEW

**Comment by guilherme-diniz** [comment]
Added the same fix for header size (#1475 )
Screen Shot 2020-08-25 at 17 42 15

**Comment by MatheusRV** [comment]
Open for feedback @thenanyu @tommoor could review?

**Comment by MatheusRV** [comment]
Friendly ping

**Comment by tommoor** [comment]
Howdy – the idea of being able to see when a document moved is valuable but I don't think it deserves it's own timeline separate to the document history – it should just be included in the same timeline as you commented above.

With this particular implementation it doesn't make sense to render the admin list component in the sidebar here, it means the name of the document is repeated over and over again – the IP address is also kind of rendered half off-screen.

What problem is this solving, which events are you particularly interested in?

**Comment by tommoor** [comment]
closing based on feedback and lack of movement, this idea will be kept around though and I think a combined timeline makes sense for the future

**Pull request closed without merging**
