### PR TITLE
Add ability to sync groups with OIDC provider

### PR DESCRIPTION
**Pull request by Shuttleu**
Currently there is no way to sync groups between OIDC and outline groups.

Adding a env var `OIDC_GROUPS_CLAIM` that, if set, will add any missing groups and add the user to them, then remove them from any groups they should no longer be in.

If the env var is not set, nothing will happen, so this entirely opt in.

### CODE REVIEW

**Comment by tommoor** [comment]
Hi @Shuttleu – thank you for the contribution, unfortunately this functionality won't be merged into the community edition as we are planning on adding group syncing for all SSO providers as part of the licensed edition. You can, of course, maintain your fork with this functionality.

Again, appreciate the work but this is a good reason why following the [contribution guidelines](https://github.com/outline/outline#contributing) and creating an issue for discussion first is important.

**Comment by Shuttleu** [comment]
👌

**Comment by TobiasGrether** [comment]
@tommoor Is it known when we can expect this to be added to the licensed edition?

**Comment by tommoor** [comment]
In terms of roadmap, we're working on collection sharing first, then this :) 

https://docs.getoutline.com/s/roadmap

**Pull request closed without merging**
