### PR TITLE
add self-host Gitlab Snippets

### PR DESCRIPTION
**Pull request by TaoChan1005**
add self-host Gitlab Snippets. 

It needs to set env -> CSP_ALLOW_SITE = xxxx

image

image

### CODE REVIEW

**Comment by almereyda** [comment]
@TaoChan1005 I like your feature and would like to test it. Could you rebase against current `main`?

Please note there have been serious refactors around the way how integrations with custom domain are handled. Please refer to the Draw.io and Grist examples, in case you feel this is still a useful addition.

I would then be able to check out this branch, test it and provide feedback.

**Comment by TaoChan1005** [comment]
> @TaoChan1005 I like your feature and would like to test it. Could you rebase against current `main`?
> 
> Please note there have been serious refactors around the way how integrations with custom domain are handled. Please refer to the Draw.io and Grist examples, in case you feel this is still a useful addition.
> 
> I would then be able to check out this branch, test it and provide feedback.

I think it works now.

**Comment by almereyda** [comment]
Thanks, I will look into the proposed functionality.

I guess we would need qualified response from @tommoor or another maintainer about the newly introduced `CSP_ALLOW_SITE` variable and associated logic.

**Comment by TaoChan1005** [comment]
Now it should work.

**Comment by almereyda** [comment]
This is working nicely now:

grafik

A pity to find that GitLab doesn't render Markdown here [¹](https://gitlab.com/gitlab-org/gitlab/-/issues/22433).

In addition, would there be a way that this integration also shows a bottom bar like in https://github.com/outline/outline/issues/6451#issuecomment-1917956335?

It could read:

> GitLab Snippet - <Title of the snippet> (because that's not shown) and ultimately also an **:link: Open** link.

Does this pattern seem useful to stabilise for Outline embeds?

**Comment by tommoor** [comment]
We really need to get rid of this giant border around GitLab embeds, I'm frustrated that these got merged in that state – it's my mistake I didn't notice because of testing in light mode.

**Comment by IamTaoChen** [comment]
https://github.com/IamTaoChen/outline/tree/gitlab_new

**Comment by almereyda** [comment]
The latest release https://github.com/outline/outline/releases/tag/v0.76.0 also has a commit that works with the GitLab snippets: https://github.com/outline/outline/commit/8b6a760e02a5a30d4f08db9e34682fb4d6840f0a

`gitlab_new` would eventually have to be rebased against `0.76.0` or `main` to incorporate these changes.

I've linked here from

- https://github.com/outline/outline/issues/6795#issuecomment-2090549993

as well for sake of completeness.

**Comment by almereyda** [comment]
There is also a proposed solution to removing the large border around GitLab embeds, as mentioned above, in:

- https://github.com/outline/outline/pull/6217#issuecomment-1828880788

**Pull request closed without merging**
