### PR TITLE
feat: Embed Google Drive

### PR DESCRIPTION
**Pull request by mxzinke**
Because #1702 has some issues, I pick it up and repair it.

### CODE REVIEW

**Review by tommoor — APPROVED** [review]
This looks good, I'm not sure if the regex will end up being a touch strict but that can be tweaked later if need be. e.g. there may be other query parameters that are possible.

I'm not sure why CI isn't running on this branch – it should be.

**Comment by mxzinke** [comment]
Sorry for inconvenience, but I did found another issue with my regex and that I should only show the preview. Maybe you can look at my last two commits again.

If everything ready, would be nice to directly merge (I have no write access).

**Comment by tommoor** [comment]
I'll test this locally again before EOW and merge if all is well

**Comment by mxzinke** [comment]
FIY: The pipeline is maybe disabled at CircleCI for forked repositories. You can enabled it back, explained like here: https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories

**Comment by tommoor** [comment]
That setting has been enabled for some time 🤷

**Comment by MatheusRV** [comment]
Waiting Anxiously, closing #1702

**Pull request merged**
