### PR TITLE
feat: MVP for Reaction and Comments using Disqus (WIP) (Help Needed)

### PR DESCRIPTION
**Pull request by MatheusRV**
Since is possible to use Disqus to use reactions and comments that's a good MVP for issues https://github.com/outline/outline/issues/1326 and https://github.com/outline/outline/issues/457

- [x] Improve Disqus Script
- [x] Add Disquis_Shortname in env
- [X] Inject disqus in page

### CODE REVIEW

**Comment by MatheusRV** [comment]
Refused to load the script 'https://rock-wiki.disqus.com/embed.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' gist.github.com www.google-analytics.com browser.sentry-cdn.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by tommoor** [comment]
Hi @MatheusRV – thanks for your efforts but we're not going to bring this into the main project, comments will be a first-party concern (the work has begun) and we're not interested in introducing a third-party dependency for this.

Of course you're welcome to keep this functionality on your fork!

**Comment by kamal0808** [comment]
@tommoor Is there a pull request or branch I can contribute to?

**Comment by matbrgz** [comment]
@kamal0808 here https://github.com/outline/outline/issues/457

**Pull request closed without merging**
