### PR TITLE
chore: Remove env variables in webpack bundle

### LINKED ISSUE #1351: Remove env variables baked into webpack
A big request from folks self hosting has been to remove the webpack build step inside the docker container for lower memory usage and faster startup.

The main thing that needs to happen to achieve this is to move the dynamic values out of the built javascript bundle and into the rendered html page, inside a script tag.

See this previous (unlanded) PR for reference https://github.com/outline/outline/pull/850

### PR DESCRIPTION
**Pull request by tommoor**
Local testing has gone well, I don't know if any folks self hosting want to give this a try? I'll leave it open for feedback until the weekend. 

closes #1351 
relates #1177
relates #850

### CODE REVIEW

**Comment by defunctzombie** [comment]
Sorry I hadn't gotten around to making a PR for the referenced docker image PR - but if you wanted to keep your env vars during the build you can accomplish this using docker build ARGS as seen here:

https://github.com/Polychain/outline/blob/v0.43.3-pc0/Dockerfile

**Comment by tommoor** [comment]
@defunctzombie honestly I prefer the approach of not having them in the bundle at all, it's easier to understand – we've had a few cases of folks tripped up by doing the webpack build in an environment without the variables and it'll be nice to take that out of the equation.

**Comment by defunctzombie** [comment]
Absolutely - you know best what makes sense for the project. I wanted to provide the Dockerfile as an option since I had noted earlier that I would.

On the PR itself - something I've found helpful is to consolidate the config into a single file (config.js, env.js, etc) and use that in various locations rather than "window.env". It allows for a single place to document and simpler management of how the environment configuration is loaded (today from window, maybe tomorrow elsewhere) and avoid the window global sprinkled around the project files. Since you are already touching many of these locations now might be a nice time to make such a change.

**Comment by tommoor** [comment]
Good call on the consolidation 👍

**Pull request merged**
