### PR TITLE
feat: Personal collection

### PR DESCRIPTION
**Pull request by tommoor**
Provides a private space to write docs that is not visible to other team members by default. Another spike that was sat on a branch and could be completed

### CODE REVIEW

**Comment by wvds** [comment]
@tommoor Is this something that is still being considered? Currently we're using drafts to have somewhat personal notes, but a private space for person would be a nice addition!

**Comment by tommoor** [comment]
Yea, would still love to have something like this

**Comment by JezzRDZ** [comment]
@tommoor is this feature still on the table?

**Comment by tommoor** [comment]
Yea, we should still do this

**Pull request closed without merging**
