### PR TITLE
fix: Draft doc are readable by collection member through URL

### PR DESCRIPTION
**Pull request by iamsaumya**

### CODE REVIEW

**Comment by tommoor** [comment]
This is actually by design 😬 – so you can share an in-progress draft with team members. It's possible we could lock it down further when per-document sharing is built

**Comment by iamsaumya** [comment]
Ohh 🤦🏻‍♂️

**Comment by iamsaumya** [comment]
Should they be able to update and delete it too?

**Comment by tommoor** [comment]
Update is okay, for collaboration – delete maybe not? This issue is going to disappear with your other PR anyway

**Pull request closed without merging**
