### PR TITLE
feat: Add Google Calendar Embed

### PR DESCRIPTION
**Pull request by matbrgz**

### CODE REVIEW

**Comment by tommoor** [comment]
Hey, as mentioned previously on #2195 we cannot merging "embeds" that just iframe an entire existing website. The embed must offer unique functionality that is designed to be embedded within another page.

**Comment by matbrgz** [comment]
Hello Tom, Google Calendar is designed for embed solutions too as described in Google Documentation(https://support.google.com/calendar/answer/41207?hl=en).

image

**Comment by tommoor** [comment]
@matbrgz this specifically points to an `/embed/` url though

**Comment by matbrgz** [comment]
@iamsaumya could you please fix this implementation?

**Pull request closed without merging**
