### PR TITLE
feat: generic frame

### PR DESCRIPTION
**Pull request by milesstoetzner**
Hello, 

I implemented an Integration that basically accepts any URL as iframe src.
See "Any URL" in https://github.com/outline/outline/issues/817#issuecomment-653703111.

Screenshot from 2021-01-16 14-08-10

### CODE REVIEW

**Comment by milesstoetzner** [comment]
okay there might be a problem. 

other integrations are replaced by this generic frame integration after rerendering a page.
I assume that this happens since the generic frame basically accepts any url.

Not familiar with the integration selection algorithm but I guess some kind of longest prefix matching would be working.

**Comment by tommoor** [comment]
Yes, I think you have found the problem with this – not only other integrations will be replaced but every url in all existing documents which would cause many to break.

In order to achieve this we'd need a way to mark that urls should be considered an "embed" beyond the current method of checking if the url and alt text are identical. We could probably use a similar method to what was [just used for image alignment](https://github.com/outline/rich-markdown-editor/pull/345), storing the metadata in the title part of the markdown string. This work would need to be done in the `rich-markdown-editor` repo.

**Comment by MatheusRV** [comment]
@milesstoetzner nice work, you could try to start with others simplest embedded. But still helping make Outline the best knowledge base.

**Comment by tommoor** [comment]
closing this out as it'll need more work in the editor before being mergable, feel free to reopen if it gets there

**Comment by matbrgz** [comment]
@tommoor  Is possible to re-open this? Since #2302 is done.

**Comment by michalkos** [comment]
Would love to see this re-opened.

**Pull request closed without merging**
