### PR TITLE
chore: Improve performance in dev by running Node/Yarn outside of docker

### PR DESCRIPTION
**Pull request by tommoor**
You may have to update your `.env` to point to localhost as in the sample changes, but other than that it should "just work".

One of the points raised in this discussion thread:
https://github.com/outline/outline/discussions/1269

### CODE REVIEW

**Comment by tommoor** [comment]
cc @gempain

**Comment by gempain** [comment]
(whoops, didn't think it'd actually accept my review 😛 , sorry !)

**Comment by tommoor** [comment]
I'm thinking I might change all the ports away from non-standard ones, because anyone that's running postgres/redis locally on their mac already (seems very possible) will have conflicts

**Comment by gempain** [comment]
I would advise against it and leave the default ports. Most people would expect those ports. Most generally, it's better to leave it to end users to customize the ports how they want it IMO.

**Pull request merged**
