### PR TITLE
Toggle visibility of comment UI based on policy

### LINKED ISSUE #5142: Toggle comment functionality based on policy
[Follow up](https://github.com/outline/outline/pull/5130#pullrequestreview-1367872813) of #5130

### PR DESCRIPTION
**Pull request by apoorv-mishra**
Closes #5142

### CODE REVIEW

**Comment by tommoor** [comment]
We want to retain the ability to view comments with this policy, just not create comments. So the only UI that should be hidden is:

- The reply input on comment threads
- The comment input at the bottom of the sidebar
- The button in the floating editor toolbar

**Review by tommoor — CHANGES_REQUESTED** [review]
Requesting changes properly so you can request re-review.

**Comment by tommoor** [comment]
There's no changes in this PR now 😆

**Comment by apoorv-mishra** [comment]
Paused! Working on a different issue for now.

**Pull request merged**
