### PR TITLE
fix: show complete page without scrollbar in print view

### LINKED ISSUE #6615: Print wiki page shows a scroll
If I want to print a page using Edge/Chrome it shows a scroll.

image

However in Firefox works well

image

### PR DESCRIPTION
**Pull request by Pranav2612000**
Fixes #6615

### CODE REVIEW

**Comment by Pranav2612000** [comment]
As a temporary fix, I've unset the height when trying to print the document. But a more holistic solution can be to check if we need to set `height: 100vh` for the MobileScrollWrapper

**Comment by Pranav2612000** [comment]
Or we can also update the `useMobile` hook to return false when opening the document for print by updating the condition in `useMobile.ts`

**Comment by tommoor** [comment]
I would do that later one yea, check print in useMobile

**Comment by Pranav2612000** [comment]
@tommoor updated the PR. can you take a look now?

**Review by tommoor — APPROVED** [review]

**Pull request merged**
