### PR TITLE
feat: Optimize Dockerfile

### PR DESCRIPTION
**Pull request by lolPants**
## Dockerfile Improvements
* Use new BuildKit dockerfile syntaxes
* Leverage multi-stage build steps for faster builds
* Strip Yarn install cache from image, reducing final size
* Use a stricter version of `yarn install` such that it will fail with an invalid lockfile
* Run as a non-root user for security

## Notes
* `yarn-deduplicate` was moved to a required dependency, otherwise running `yarn install --production` will fail on fresh installs.
* In my testing the image sizes were reduced from ~1.4GB to ~450MB

### CODE REVIEW

**Comment by tommoor** [comment]
> yarn-deduplicate was moved to a required dependency, otherwise running yarn install --production will fail on fresh installs.

Hmm, okay this makes sense – we probably need to change this so that deduplicate only runs in dev if possible. Running it after a frozen lockfile defeats the purpose a little.

> In my testing the image sizes were reduced from ~1.4GB to ~450MB

Very cool

**Comment by lolPants** [comment]
> Hmm, okay this makes sense – we probably need to change this so that deduplicate only runs in dev if possible. Running it after a frozen lockfile defeats the purpose a little.

I believe the `prepare` script does exactly this, running only when `--production` is not specified. Alternatively you could craft a script leveraging `NODE_ENV` and only running deduplication when set to `production`.

**Comment by tommoor** [comment]
Great idea on `prepare`, I've updated this on `main`

**Comment by lolPants** [comment]
Updated the PR to revert the change to `yarn-deduplicate`, double-checking the image builds as expected and then this should be good to merge.

**Comment by lolPants** [comment]
All looks good on my end!

**Comment by tommoor** [comment]
Testing this now, did most of the size saving come from the cache removal as far as you can tell?

**Comment by lolPants** [comment]
That certainly helps a lot, but Docker build layers are additive, so installing dev-deps and then removing them in a later step will still retain the full size of said deps. Leveraging multi-stage builds you can use dev-deps to build in a different step and copy in the prod deps to the final image.

**Comment by tommoor** [comment]
This pre-release includes these Dockerfile changes if you wanted to try:

`docker pull outlinewiki/outline:version-0.58.0-4`

**Pull request merged**
