### PR TITLE
Fix: negative numbers in pagination (limit/offset)

### PR DESCRIPTION
**Pull request by drezo**
Hello 🖖

This method returns an error 😞 (500 HTTP Code): 

POST /api/documents.list?limit=**-20**&offset=**-10**

**Example:**

outline_screenshot

### CODE REVIEW

**Comment by tommoor** [comment]
Thanks for finding this. I think the better approach here would be to throw an error similar to L26 explaining that limit and offset must be positive numbers, rather than silently reversing them – thoughts?

**Comment by drezo** [comment]
@tommoor 

Yes, as an option. 

But in this case, you need to write an error if the passed parameter is not a number.

_Example:_

POST /api/documents.list?limit=**text20text**&offset=**text20text**

_Response:_

outline_pagination

**Comment by tommoor** [comment]
> But in this case, you need to write an error if the passed parameter is not a number.

I think that would be great if the two were brought in-line. An `isNaN` check would do the trick

**Comment by tommoor** [comment]
Thanks for finding this bug, the issue has been fixed with tests here: 0a8a685c

**Pull request closed without merging**
