### PR TITLE
feat: Custom Length decorator for UTF-8 chars len 

### LINKED ISSUE #3705: Attempting to import a document through `ImportTask` with a title longer than 100 chars results in error
**To Reproduce**
1. Create a document in Notion with a title longer than 100 chars
2. Create export
3. Attempt to import into Outline
4. Error importing.

**Expected behavior**

- The title should be chopped to the maximum allowable characters

### PR DESCRIPTION
**Pull request by CuriousCorrelation**
## Description
Fixes error when importing document through `ImportTask` with a title longer than 100 chars.

Uses same strategy as in

https://github.com/outline/outline/blob/68dd76cfa37cc4559ffc323937456b8afb652889/server/commands/documentImporter.ts#L224

## Issue
Closes #3705

### CODE REVIEW

**Comment by tommoor** [comment]
That's correct, the base class is an abstract class and as such can't be instantiated. Adding a test to eg the Notion importer would work well 👍

**Comment by tommoor** [comment]
Sorry, bug in GitHub keeps closing PR's when I comment 🙄

**Comment by CuriousCorrelation** [comment]
Haha no worries at all.

---

`ImportNotionTask` uses `documentImporter` to set title

https://github.com/outline/outline/blob/930bfd5391c93352374b85f1409085e1b1a2e6f4/server/queues/tasks/ImportNotionTask.ts#L93

and `documentImporter`

https://github.com/outline/outline/blob/68dd76cfa37cc4559ffc323937456b8afb652889/server/commands/documentImporter.ts#L224

correctly truncates the long title. So I think any tests added to `ImportNotionTask` will pass regardless. Should I add one anyway or is there another way to isolate `ImportTask` for this case? Not 100% sure.

**Comment by tommoor** [comment]
so, looking at it now I don't think this is the correct solution in that case. The argument passed to documentCreator can only come from that documentImporter and should already be truncated. 

Definitely need some tests to figure out what's going on – maybe one place is doing < max_length and another is doing <= max_length.

**Comment by CuriousCorrelation** [comment]
Makes sense and

> maybe one place is doing < max_length and another is doing <= max_length.

seems the likely culprit. 
I'll do some digging and let you know what I find.

**Comment by tommoor** [comment]
> I changed the title of first file in notion-markdown.zip to one with 160 chars and re-ran tests

Same here, it's a weird one – perhaps a character encoding issue or something. Will try and get hold of the original data that caused the error

**Comment by tommoor** [comment]
Okay, it is indeed a UTF-8 character issue. In this case it's the "🛡️" character which lodash truncate is counting as `1` but the database validation is counting as `3`

image

For this particular usecase the lodash version is more "correct" and therefore the bug/problem is in the sequelize validation library.

**Comment by tommoor** [comment]
So the solution is to change `Length` to use a custom validation that measures the string with https://lodash.com/docs/4.17.15#size

**Comment by CuriousCorrelation** [comment]
That was indeed the issue! This patch should work now. 

I changed the commit message to `feat` instead of `fix` and also added a test to specifically check for UTF-8 char length. 

Let me know if there's something that needs a second look.

**Comment by tommoor** [comment]
Just need to run `yarn lint --fix` to reformat that file and fix the build, looks like you did a great job here

**Comment by CuriousCorrelation** [comment]
> Just need to run `yarn lint --fix` to reformat

Oops forgot about that. Latest commit should fix that.

**Review by tommoor — APPROVED** [review]

**Comment by tommoor** [comment]
@CuriousCorrelation thanks for taking this on. If you're interested in taking on other issues (and getting paid if you like) hit me up.

**Comment by CuriousCorrelation** [comment]
I would love to, it sounds like an exciting opportunity (with perfect timing)! 

I can drop an email or message via preferred comms channel, just let me know when and where.

**Pull request merged**
