### PR TITLE
Feat: add GitLab authentication

### PR DESCRIPTION
**Pull request by almereyda**
This adds GitLab authentication support to Outline.

It is based on #2101 by @ChetanGoti and adds the groups support prototyped in https://github.com/jakoblorz/outline/pull/2.

### CODE REVIEW

**Comment by almereyda** [comment]
The donation of this PR is a Sunday afternoon's project to congratulate for the latest merge of real-time collaboration.

**Comment by dmezh** [comment]
You could also accomplish this with GitLab as an OIDC provider. Personally not sure of the utility of maintaining Gitlab as a separate auth strategy besides the groups support, which I think someone was going to add to the OIDC strategy here https://github.com/outline/outline/pull/2568.

**Comment by almereyda** [comment]
The last commit removes the `request` helper function from the GitLab authentication provider, as proposed and implemented through #2594. From my side I assume this branch is mergeable.

---

I consider having a native connector useful, due to requiring less boilerplate for a connection between the platforms, and offering the GitLab icon as a hint to the user where they are originating from.

Indeed if #2568 helps to use groups support through the generic OIDC provider already, and helps us to avoid adding another dependency to `package.json`, I'm happy to follow that route instead. Will we be able to set a custom icon on OIDC Login Buttons?

Additionally, this kind of addon here, one that adds dependencies, might also be a good chance to try out approaches for #2219 instead.

---

As a side note, if this would be merged, we'd happily run an instance with different Teams for authenticated GitLab groups. Until this is not available on `main`, it remains a blocker for us.

**Comment by EternalDeiwos** [comment]
I am not sure if Gitlab provides group information on the JWT; in fact I'm pretty sure they don't, in which case #2568 isn't going to help with that.

**Comment by almereyda** [comment]
I have tested #2568 with a merged `main` against an existing OIDC connection with GitLab and can confirm that a very small number of the groups associated with the username logging in have indeed been created automatically, yikes!

Apparently there is an error with the group creator that times out

```
[api] ConnectionAcquireTimeoutError [SequelizeConnectionAcquireTimeoutError]: Operation timeout
[api]     at ConnectionManager.getConnection (/srv/idata/src/github.com/outline/outline/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:288:48)
[api]     at runNextTicks (internal/process/task_queues.js:60:5)
[api]     at listOnTimeout (internal/timers.js:526:9)
[api]     at processTimers (internal/timers.js:500:7)
[api]     at async Transaction.prepareEnvironment (/srv/idata/src/github.com/outline/outline/node_modules/sequelize/lib/transaction.js:119:24)
[api]     at async Sequelize.transaction (/srv/idata/src/github.com/outline/outline/node_modules/sequelize/lib/sequelize.js:1082:7)
[api]     at async groupCreator (/srv/idata/src/github.com/outline/outline/build/server/commands/groupCreator.js:33:23)
[api]     at async Promise.all (index 5)
[api]     at async accountProvisioner (/srv/idata/src/github.com/outline/outline/build/server/commands/accountProvisioner.js:132:14)
[api]     at async OAuth2Strategy._verify (/srv/idata/src/github.com/outline/outline/build/server/routes/auth/providers/oidc.js:100:22) {
[api]   parent: TimeoutError: Operation timeout
[api]       at Timeout.<anonymous> (/srv/idata/src/github.com/outline/outline/node_modules/sequelize-pool/lib/Deferred.js:17:25)
[api]       at listOnTimeout (internal/timers.js:557:17)
[api]       at processTimers (internal/timers.js:500:7),
[api]   original: TimeoutError: Operation timeout
[api]       at Timeout.<anonymous> (/srv/idata/src/github.com/outline/outline/node_modules/sequelize-pool/lib/Deferred.js:17:25)
[api]       at listOnTimeout (internal/timers.js:557:17)
[api]       at processTimers (internal/timers.js:500:7)
[api] }
[api] TypeError: Cannot read property 'map' of undefined
[api]     at accountProvisioner (/srv/idata/src/github.com/outline/outline/build/server/commands/accountProvisioner.js:151:32)
[api]     at runNextTicks (internal/process/task_queues.js:60:5)
[api]     at listOnTimeout (internal/timers.js:526:9)
[api]     at processTimers (internal/timers.js:500:7)
[api]     at async OAuth2Strategy._verify (/srv/idata/src/github.com/outline/outline/build/server/routes/auth/providers/oidc.js:100:22)
```

but already looks almost usable.

Also it seems that emails are sent synchronously during the callback, but that should be another issue.

**Comment by almereyda** [comment]
GitLab can be integrated as an OIDC provider. It does not get the lovely icon, but that's about all that's missing.

**Pull request closed without merging**
