### PR TITLE
fix: valid links in export

### LINKED ISSUE #2370: Exports generate invalid links
Exports generate markdown links which do not resolve to the proper paths.  

In the export extraction below, for example, each link points to a `/doc` directory however there is no such directory, and no such file. 

```
* [Benefits](/doc/benefits-NRveSbzJ7x)
* [HR Policies and Resources](/doc/hr-policies-and-resources-jrEdwegbp7)
* [Vacation and Holidays](/doc/vacation-and-holidays-WJVgOQvXys)
```

**Expected behavior**

My expectation is that simple Markdown links would be generated, relative to the location of the referencing file.

```
* [Benefits](Benefits.md)
* [HR Policies and Resources](HR Policies and Resources.md)
* [Vacation and Holidays](Vacation and Holidays.md)
```

Extra special credit would be having an option to generate wiki-style links like [[Benefits]]

**Outline (please complete the following information):**
- Install: getoutline.com

### PR DESCRIPTION
**Pull request by iamsaumya**
closes #2370 

 - [x] Remove currentColor from Outline icon of Import page

### CODE REVIEW

**Comment by iamsaumya** [comment]
Two edges cases: filename shouldn't contain `#` and should have balanced parenthesis.

**Comment by iamsaumya** [comment]
I wrote a test. Please do let me know if it will suffice.

**Comment by tommoor** [comment]
So, I [rebuilt the import processor](https://github.com/outline/outline/pull/3434) partially because of this PR – I believe that it works but the way it's structured makes it very difficult to reason about – there is data and paths passed all over the place.

Not sure if you're interested in bringing this fix across or not, I'd understand if not.

**Comment by iamsaumya** [comment]
Tom, I'm always interested. Haven't read that whole PR yet but so far looks is a work of art 👌

**Pull request closed without merging**
