### PR TITLE
feat: Proxy-managed auth

### PR DESCRIPTION
**Pull request by Mubelotix**
That allows self-hosters to put their instance behind a proxy (like nginx) and plug their custom authentication server

<details>
<summary>Example nginx config file</summary>

```nginx
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name {{ webserver_domains | join(' ') }};

    ssl_certificate /etc/letsencrypt/live/{{ service_name }}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{ service_name }}/privkey.pem;
    
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    client_max_body_size 50M;

    # Exclude some locations from auth
    location ~ ^/(static|locales|fonts|images)/ {
        proxy_pass http://127.0.0.1:{{ outline_inner_port }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }

    # WebSocket support
    location ~ ^/(realtime|collaboration) {
        auth_request /auth;
        auth_request_set $insa_auth_email $upstream_http_x_insa_auth_email;
        auth_request_set $insa_auth_uid $upstream_http_x_insa_auth_uid;
        auth_request_set $insa_auth_uid_number $upstream_http_x_insa_auth_uid_number;
        auth_request_set $insa_auth_groups $upstream_http_x_insa_auth_groups;
        auth_request_set $insa_auth_given_name $upstream_http_x_insa_auth_given_name;
        auth_request_set $insa_auth_family_name $upstream_http_x_insa_auth_family_name;
        proxy_set_header X-Insa-Auth-Email $insa_auth_email;
        proxy_set_header X-Insa-Auth-Uid $insa_auth_uid;
        proxy_set_header X-Insa-Auth-Uid-Number $insa_auth_uid_number;
        proxy_set_header X-Insa-Auth-Groups $insa_auth_groups;
        proxy_set_header X-Insa-Auth-Given-Name $insa_auth_given_name;
        proxy_set_header X-Insa-Auth-Family-Name $insa_auth_family_name;
        proxy_set_header X-Insa-Full-Name "$insa_auth_given_name $insa_auth_family_name";
        proxy_set_header X-Team-ID "eb4ea2b8-d62c-4376-a2a5-c20787d1c824";
        proxy_set_header X-Lang "fr_FR";

        proxy_pass http://127.0.0.1:{{ outline_inner_port }};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400; # 24 hours
    }
    
    location / {
        auth_request /auth;
        auth_request_set $insa_auth_email $upstream_http_x_insa_auth_email;
        auth_request_set $insa_auth_uid $upstream_http_x_insa_auth_uid;
        auth_request_set $insa_auth_uid_number $upstream_http_x_insa_auth_uid_number;
        auth_request_set $insa_auth_groups $upstream_http_x_insa_auth_groups;
        auth_request_set $insa_auth_given_name $upstream_http_x_insa_auth_given_name;
        auth_request_set $insa_auth_family_name $upstream_http_x_insa_auth_family_name;
        proxy_set_header X-Insa-Auth-Email $insa_auth_email;
        proxy_set_header X-Insa-Auth-Uid $insa_auth_uid;
        proxy_set_header X-Insa-Auth-Uid-Number $insa_auth_uid_number;
        proxy_set_header X-Insa-Auth-Groups $insa_auth_groups;
        proxy_set_header X-Insa-Auth-Given-Name $insa_auth_given_name;
        proxy_set_header X-Insa-Auth-Family-Name $insa_auth_family_name;
        proxy_set_header X-Insa-Full-Name "$insa_auth_given_name $insa_auth_family_name";
        proxy_set_header X-Team-ID "eb4ea2b8-d62c-4376-a2a5-c20787d1c824";
        proxy_set_header X-Lang "fr_FR";

        proxy_pass http://127.0.0.1:{{ outline_inner_port }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }

    location = /auth {
        internal;
        proxy_pass https://auth.insa.lol/verify;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
        proxy_intercept_errors on;
        error_page 401 = @error401;
    }

    # When auth fails, complete the request without auth headers.
    # You could also just redirect to the auth server but that would block unauthenticated web access. 
    location @error401 {
        proxy_pass http://127.0.0.1:{{ outline_inner_port }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Insa-Auth-Email "";
    }
}
````
</details>

### CODE REVIEW

**Comment by Mubelotix** [comment]
@tommoor Hello?

**Comment by tommoor** [comment]
Hi, thanks for your efforts. I won't be merging at this time – there are honestly already too many authentication options in this platform and each one adds potential vulnerabilities. We already support custom authentication servers through OAuth, OIDC, and SAML.

**Comment by max-tet** [comment]
That is really unfortunate IMO. I think proxy-auth should be a standard feature of any web application. The flow for the user is just even more simple and transparent than with other auth options.

Honestly, this is what breaks Outline for my use-case. I have a auth setup in place and many apps that are seamlessly accessed with a single login using proxy-auth. Outline would be a great addition but I don't want users to have to login again.

It would be really great if you could reconsider.

**Comment by Mubelotix** [comment]
> That is really unfortunate IMO. I think proxy-auth should be a standard feature of any web application. The flow for the user is just even more simple and transparent than with other auth options.
> 
> Honestly, this is what breaks Outline for my use-case. I have a auth setup in place and many apps that are seamlessly accessed with a single login using proxy-auth. Outline would be a great addition but I don't want users to have to login again.
> 
> It would be really great if you could reconsider.

I'm keeping my fork up to date fyi. Please note that my implementations occasionally creates a duplicated user for new users but it's easy to remove them manually

**Pull request closed without merging**
