### PR TITLE
fix: Two restore options when an archived document is deleted

### PR DESCRIPTION
**Pull request by iamsaumya**
This PR fixes the bug of two restore options showing in the document menu when an archived document is deleted.

### CODE REVIEW

**Comment by iamsaumya** [comment]
There is another bug that will require one line of change. Should I create a separate PR or fix it here?

**Comment by tommoor** [comment]
Feel free to add the fix on

**Comment by iamsaumya** [comment]
In my DB, the parentDocumentId was not updating to null when we assigned with `undefined`

**Comment by tommoor** [comment]
The test wasn't passing locally? 🤔

**Comment by iamsaumya** [comment]
Ahh! I have been encountering this issue for the last week, I guess. Something is wrong with circleCI.

**Comment by tommoor** [comment]
Sorry, I mean before you made this change was the test not passing with `undefined`? It should act the same.

This other test failure is sporadic on CI, it needs addressing :(

**Comment by iamsaumya** [comment]
For that, I did not check at my localhost.

**Review by tommoor — APPROVED** [review]

**Pull request merged**
