### PR TITLE
feat: TOC position for publicly shared docs

### LINKED ISSUE #7055: Respect TOC position preference on shared docs
Currently only on internal docs but should be easy enough to expose preference to shared pages.

Related https://github.com/outline/outline/issues/6383
Related https://github.com/outline/outline/pull/6943

### PR DESCRIPTION
**Pull request by hmacr**
Closes #7055

### CODE REVIEW

**Comment by tommoor** [comment]
That was fast, ha. Lets just use the existing `presentPublicTeam` which is there to expose a selection of team preferences rather than add another object type

**Comment by hmacr** [comment]
Since `PublicTeam` holds the custom team branding info, I added a new object (doesn't have a link with custom branding). This could have other misc preferences we want to support in the future as well.

Do you think we should stick with the `PublicTeam` object?

**Comment by tommoor** [comment]
I can see the logic, I think it's fine to use `PublicTeam` here – it's maybe a bit badly named in retrospect but can consider the toc position to be part of the "branding" in a way.

**Comment by hmacr** [comment]
With this change, the toc-position is customized when the team opts into branding.

**Review by tommoor — APPROVED** [review]

**Pull request merged**
