### PR TITLE
feat: Templates

### LINKED ISSUE #44: Templates
Just a little issue to keep track of ideas / implementation for this feature.

### PR DESCRIPTION
**Pull request by tommoor**
### Todo

- [x] Add collection name to breadcrumb for template
- [x] Add ellipsis "+ New doc…" when button has flyout
- [x] Add "New from template" button to header of template on right hands side
- [x] Store which template a document came from `templateId`
- [x] Make creating a template copy the original instead of replace it
- [x] Move "Templates" filter to right hand side on collections list
- [x] Remove public share option for templates and revoke existing shares
- [x] Add "New doc" button to template list items
- [x] Add nested menu from "New doc" when collection has templates
- [x] Fix sorting on templates list
- [x] Double check language on template confirmation modal
- [x] Add onboarding for editing placeholders/templates
- [x] Delete key at the end of a placeholder should remove entire placeholder
- [x] Doc from template titles
- [x] Fix policies not being returned from templatize

closes #44

### CODE REVIEW

**Comment by tommoor** [comment]
### Progress…

image

**Comment by tommoor** [comment]
image

image

**Comment by 07Gond** [comment]
Looks amazing! 👏

**Comment by tommoor** [comment]
Changed up the main flow for creating a new document from template to be less cumbersome and not introduce new flyout menus. It's now an option on newly created docs, like so:

image

The content in the doc seamlessly swaps out, which feels quite nice.

**Pull request merged**
