### PR TITLE
CMD+S in a new document should not exit edit mode

### PR DESCRIPTION
**Pull request by zacharyfmarion**
Hey guys! Jori especially ;). This project looks awesome! I wanted to get involved if possible so I set it up today. This is a tiny PR to address issue #493. It's a little weird to have the text be Publish when in fact you are just saving, so I'm not sure if this fix is sufficient. Generally there is a publish/save distinction if you can have content that is visible to you in draft form but is not ready for the group to see yet. Also it doesn't look like there are component level tests so I didn't write one, hopefully that's okay!

### CODE REVIEW

**Comment by tommoor** [comment]
Hey @zacharyfmarion ! 

You're right about the publish text – the idea here is definitely to introduce the ability to save without publishing but we'll also need to have a sidebar item to view those 'drafts', there's an issue for that here: https://github.com/outline/outline/issues/40

As far as the PR goes - makes sense, it's so obvious I wonder why it was ever like this 🧐

**Comment by zacharyfmarion** [comment]
Okay I see so expected behavior is that is should still redirect to the new page, the editor should just be focused one the redirect occurs?

**Comment by jorilallo** [comment]
A wild @zacharyfmarion appears! Good to see you again buddy :)

**Comment by zacharyfmarion** [comment]
Hey @jorilallo good to see you too! I'm gonna be pretty bored over winter break so feel free to assign some issues to me if you think I'd be a good fit.

**Comment by tommoor** [comment]
>  Also just to clarify, clicking the publish button should exit edit mode, correct?

Yep! I'll check out this PR soon, got a feeling it's going to cause the cursor to jump but that's actually also the case just hitting cmd+s in general right now (another issue I REALLY need to look at!)

**Comment by jorilallo** [comment]
@zacharyfmarion If you want to pick up something, there's a few "good first issue" bugs, upgrading webpack (we're still on 1.x) and also improving performance. Happy to add you to our Slack if you want, just hit me up with your email!

**Comment by zacharyfmarion** [comment]
@jorilallo Okay I'll take a look at some more. I'd love to be added to slack! It's zacharyfmarion@gmail.com

**Comment by tommoor** [comment]
Just an FYI, I've been looking at improving this further to try and remove the flash of loading screen when you cmd+s and also fix the cursor losing focus, almost there…

**Pull request merged**
