### PR TITLE
feat: Attachment of files as block to documents using s3

### PR DESCRIPTION
**Pull request by warnus**
This commit is compatible with [outline/rich-markdown-editor#624](https://github.com/outline/rich-markdown-editor/pull/624)

Same work with #2859

### CODE REVIEW

**Comment by tommoor** [comment]
Hi @warnus – thank you for the effort here, unfortunately this work is incompatible with the ongoing effort to move the editor code into this codebase (https://github.com/outline/outline/pull/2930) and as such, won't be able to be merged. One of the reasons we're doing that is to make it much faster and easier to develop features like this though!

**Comment by warnus** [comment]
Hi @tommoor . Thanks for the reply. I willl update this again to be compatible. 

By the way, I have a question. Would you check this pr? (https://github.com/outline/rich-markdown-editor/pull/624)

I want to know how to set attribute variable. I'm not familiar with prosemirror, so I'd appreciate it if you could tell me.

What I want to do is pass the file url and file title from markdown to dom.

**Comment by tommoor** [comment]
I will look, but it might not be until next week. I do not plan on maintaining the editor repo any longer – see:
https://github.com/outline/rich-markdown-editor/discussions/481

**Comment by warnus** [comment]
Oh, I' sorry. I didn't see it. Thanks for the letting me know.
So the editor is merged with the Outline project?  Or will it be a private project?
Because I really need the file upload function, so I want to develop it. 🥲

**Pull request closed without merging**
