### PR TITLE
fix: just add z-index to 'heading-actions' to cover sidebar arrow (#3009)

### PR DESCRIPTION
**Pull request by ig505gi**

### CODE REVIEW

**Comment by ig505gi** [comment]
hi! it's my first PR. I didn't know if my operation was correct. If there is something wrong, please let me know.

**Comment by tommoor** [comment]
Hi @ig505gi – thanks for the PR, there are a lot of items in the editor that can potentially go behind the sidebar collapse so it probably makes more sense to move that blocking element behind than everything else in front.

**Comment by thenanyu** [comment]
To expand on what @tommoor said, the elements that interfere include drag handles on list items, heading controls, the `+` button on blank new lines (maybe some others as well)

**Comment by ig505gi** [comment]
Hi @tommoor, @thenanyu, I decided to do so for two main reasons.

1. I considered moving sidebar toggle behind everything else by setting toggle 'z-index: -1'(maybe it's not proper?). In this situation, if we expand sidebar, we can't click it to collapse sidebar.
2.  The elements @thenanyu mentioned just appear when document is editing. However, there is no sidebar toggle when document is editing, so I think the bug just happen when previewing document. The only element that interfere I found is 'header action'...

Does this make sense?

**Comment by thenanyu** [comment]
@ig505gi the sidebar will appear when editing if the team is in live editing mode. You can turn on this feature by going to settings/features

This is going to be the standard mode going forward.

**Comment by ig505gi** [comment]
@thenanyu oh I didn't know this feature. sorry about it, I will try it again.

**Comment by tommoor** [comment]
@ig505gi thanks for your efforts - it looks like a lot of other changes from `main` have snuck onto this branch, this will need to be cleanup before it's mergable so the branch only includes your changes

**Comment by tommoor** [comment]
Hey, although there was a lot of iteration here the fix ended up quite simple and you didn't yet sign the CLA. @thenanyu fixed the issue as part of this PR: https://github.com/outline/outline/pull/3350

**Comment by ig505gi** [comment]
> Hey, although there was a lot of iteration here the fix ended up quite simple and you didn't yet sign the CLA. @thenanyu fixed the issue as part of this PR: #3350

@tommoor  Very sorry for not finishing this issue due to my personal reasons, I'll read the code and learn about it.

**Pull request closed without merging**
