### PR TITLE
Add `HEALTHCHECK` into docker image

### PR DESCRIPTION
**Pull request by tommoor**
Useful for healthchecks.

Related https://github.com/outline/outline/discussions/7051#discussioncomment-9810808

### CODE REVIEW

**Comment by IamTaoChen** [comment]
So why not add the healthy check when building image?

**Comment by tommoor** [comment]
Mmm, yes – could do. Do you know of any examples?

**Comment by IamTaoChen** [comment]
Refer #7051 , this works:
```Dockerfile
ENV PORT=3000
HEALTHCHECK --interval=3s --retries=12 CMD wget --spider http://localhost:${PORT} || exit 1
```

But if we have an endpoint for health-check, it may be better. e.g. `/health` -> 'OK'

**Comment by tommoor** [comment]
Yes, such an endpoint exists at `/_health` – it checks the database and redis connection as well.

**Comment by IamTaoChen** [comment]
wget:
```Dockerfile
HEALTHCHECK --interval=3s --retries=12 CMD wget -qO- http://localhost:${PORT}/_health | grep -q "OK" || exit 1
```
curl:
```Dockerfile
HEALTHCHECK --interval=3s --retries=12 CMD curl -f http://localhost:${PORT}/_health | grep -q "OK" || exit 1

```

**Comment by dserodio** [comment]
IMHO this probably warrants a bugfix release by itself.

**Pull request merged**
