### PR TITLE
feat: Gitea as Auth Provider

### PR DESCRIPTION
**Pull request by techknowlogick**
This PR adds the ability to use any Gitea installation as an auth provider. Gitea is a tool that allows for self-hosting of git repos. More info can be found here: https://gitea.io/en-us/

Here is a screenshot of the login experience with Gitea
Screen Shot 2020-05-11 at 4 00 05 PM

### CODE REVIEW

**Comment by techknowlogick** [comment]
Title and description have been updated to have more info, hopefully the "more information needed" label can be removed now. I've also pushed a new commit that resolves the eslint issues.

**Comment by techknowlogick** [comment]
@tommoor would you be able to provide some guidance on what information I could provide to satisfy the bot?

**Comment by tommoor** [comment]
Hey, thanks for contributing  – code-wise it's definitely all in the right vein and matches the existing implementations!

There is currently a [PR in progress](https://github.com/outline/outline/pull/1183) by several folks that moves the authentication over to passport-js. I think this is a more scalable solution for adding additional auth providers, as it seems like everyone wants something different.

As the maintainer I don't plan to merge this PR as the maintenance burden is too much (this is why we explicitly ask that folks open an issue before submitting code changes), particularly for a service that no-one has requested before. I'd encourage you to maintain your fork, which should be easy to do until the passport-js changes are merged.

**Comment by Hummer12007** [comment]
Thanks for the PR! It works like a charm. @techknowlogick Do you mind me integrating it into my personal MIT-licensed fork at https://github.com/Hummer12007/outline ?

**Pull request closed without merging**
