### PR TITLE
feat: add Page Link component to Editor #4366

### PR DESCRIPTION
**Pull request by thelicato**
I've added a new component to the editor that allows the user to create a button link to another page in the KB as detailed in this old discussion we had in January: https://github.com/outline/outline/discussions/2940

### CODE REVIEW

**Comment by tommoor** [comment]
Hi @thelicato – thanks for your efforts on this one. There are a couple of thoughts blocking me here – the main one is that I believe we need to soon have display options for every link, not just "page links" and in that sense internal links aren't really unique enough to get their own special node type.

**Comment by thelicato** [comment]
The initial idea was to allow any kind of link. After looking at GitBook I found out that it allows only to link internal pages. I think this is a winning choice because allows the user to quickly know that the linked page is **another document**.

**Comment by andrzejwp** [comment]
Hello @tommoor @thelicato is there any progress on this? I'd be happy to assist as I see this addition really valuable.

**Comment by thelicato** [comment]
@andrzejwp it was ready to be merged when I opened this PR but @tommoor thought that the component should be used for both **internal** and **external** links. I did not agree on this since the idea was just to provide a component to enhance the UX of the navigation between Outline documents. Here is the link to the discussion: https://github.com/outline/outline/discussions/2940

Since my last message I did not receive any reply from Tom so now the PR is stale.

**Comment by tommoor** [comment]
Adding new nodes is something that has to happen with great consideration as once they exist there is no going back, they need to be supported by the software forever. That's the thinking behind it – if this is simply a display option for an existing node type perhaps that's how it should be represented in the data structure as well.

The other problem to overcome with this PR is that the markdown representation is not unique, until #3000 is complete every node needs to be uniquely represented in the Markdown output so that it can be rendered correctly, as it stands the page links here will not survive export<->import, for example.

**Comment by thelicato** [comment]
@tommoor Could you tell me when do you think #3000 will be implemented? Currently we are using my forked repo internally but it is troublesome to keep the forked version updated with official Outline. A quick solution to overcome the "export<->import" problem could be to add and ID or a class to the Page Link to keep it unique:
```
[Click me](<internal link>){#page-link .page-link}
```

If you don't like it let me know if  and how I can help with #3000.

**Comment by thelicato** [comment]
Hi, is there any way I can help you to get this on the official branch or do I have to throw away my hopes on this?

**Pull request closed without merging**
