### PR TITLE
fix: Remove application/octet-stream as valid frontend mimetype

### LINKED ISSUE #2123: Remove application/octet-stream as valid frontend mimetype
Follow up to https://github.com/outline/outline/pull/2105

After further testing on Windows it seems that using this mimetype results in .bin, .com, .exe files showing as available options. Instead lets just whitelist .doc, .docx extensions explicitly. This is a frontend only change, all of the updated handling on the backend can remain the same.

### PR DESCRIPTION
**Pull request by iamsaumya**
Closes #2123

### CODE REVIEW

**Comment by tommoor** [comment]
I don't think this will work alone because of this check:

https://github.com/outline/outline/blob/69802cc9850a07fd986a9dcfda1b50549f81debd/app/stores/DocumentsStore.js#L535

Probably needs to be updated to check if the file name ends with as an alternative.

**Comment by iamsaumya** [comment]
If I am not mistaken, we have to update this for the scenario where mimetype is `application/octet-stream` and the file is `.docx`. Isn't it? Because for most of the cases the two possible mimetype of word doc is present in the array.

**Comment by iamsaumya** [comment]
I think `.includes()` alone can handle the empty string scenario here, what are your thoughts? 
https://github.com/outline/outline/blob/69802cc9850a07fd986a9dcfda1b50549f81debd/app/stores/DocumentsStore.js#L535

**Comment by tommoor** [comment]
I don't think the extension check should be docx specific, it'll be useful to be able to add other additional files by extension-only here in the future.

**Review by tommoor — APPROVED** [review]
great, thanks!

**Pull request merged**
