### PR TITLE
Add AZURE_TENANT_ID enviroment variable for specific azure tenant.

### PR DESCRIPTION
**Pull request by airbenich**
As seen here https://github.com/outline/passport-azure-ad-oauth2 the Azure plugin already has the needed code to specify an specific azure tenant when using the azure tenant login. Therefore i added an ENV variable for this.

### CODE REVIEW

**Comment by tommoor** [comment]
Open to this – it would be good to add the validation decorator to check the value is a valid FQDN

**Review by tommoor — APPROVED** [review]

**Comment by gnagy** [comment]
The docs ought to be updated as well, I couldn't get Azure login working without specifying AZURE_TENANT_ID.

https://docs.getoutline.com/s/hosting/doc/microsoft-entra-UVz6jsIOcv

**Comment by tommoor** [comment]
Yea, it should be added but honestly I'm not sure under which scenarios this is needed – we went 4 years without it. Let me know if you have insight

**Comment by gnagy** [comment]
I'm also not clear on the scenarios, but login didn't work without specifying tenant ID and there was no error either in app logs or in Azure, I just happened to find the Github issue after a good deal of googling.

**Comment by airbenich** [comment]
I'm sorry about that. The parameter should actually be optional. It also looks like this in the code. The AZURE_TENANT_ID is required in the context of a company that solves its SSO via Azure. When logging in, it should be directly visible that it is the professional login & not a private Microsoft login or any other login. This helps to make the user experience more pleasant when logging in.

**Pull request merged**
