### PR TITLE
Update mermaid to V11

### PR DESCRIPTION
**Pull request by Shuttleu**
Update Mermaid to V11 to add latest changes and graphs

### CODE REVIEW

**Comment by devinnovqube** [comment]
> The bundle size increase reveals why this upgrade has not been made - this single dependency upgrade increases the size of the entire software by 20%, which is unacceptable

Some of the new mermaid features are indeed useful. However, 20% of the size for a few features seems quite substantial. Perhaps we could find a way to allow users to choose between version 9 and version 11 when deploying the application. 

Mermaid is regularly improving, and this could certainly become an issue in the future.

**Comment by tommoor** [comment]
I added additional fixes and merged here https://github.com/outline/outline/pull/7964

**Comment by owanio1992** [comment]
@tommoor 
it's happy to see upgrade mermaid version  
I have a little question here 
does this cdn link don't need upgrade ?
https://github.com/outline/outline/blob/main/server/models/helpers/ProsemirrorHelper.tsx#L561

**Comment by tommoor** [comment]
Good call

**Pull request closed without merging**
